# encoding: utf-8
"""
@author: ccj
@contact:
"""

import os
import cv2
import random

from albumentations.core.transforms_interface import ImageOnlyTransform


class AdvancedHairAugmentation(ImageOnlyTransform):
    def __init__(self, hairs: int = 5, hairs_folder: str = "", always_apply: bool = False, p: float = 0.5):
        """
            Combine hair image to original images
        :param hairs: Type: int, the number of hair images in hairs folder
        :param hairs_folder: Type: str, the directory of hair
        :param always_apply: Type: bool, if the transforms will be always applied (default: False)
        :param p: Type: float, the probability to apply this transform if not always applied
            image is generated by combining original image and hair image
        """
        self.hairs = hairs
        self.hairs_folder = hairs_folder
        super().__init__(always_apply, p)

    def apply(self, img, **params):
        n_hairs = random.randint(0, self.hairs)

        if not n_hairs:
            return img

        height, width, _ = img.shape  # target image width and height
        hair_images = [im for im in os.listdir(self.hairs_folder) if 'png' in im]

        for _ in range(n_hairs):
            hair = cv2.imread(os.path.join(self.hairs_folder, random.choice(hair_images)))
            hair = cv2.flip(hair, random.choice([-1, 0, 1]))
            hair = cv2.rotate(hair, random.choice([0, 1, 2]))

            h_height, h_width, _ = hair.shape  # hair image width and height
            roi_ho = random.randint(0, img.shape[0] - hair.shape[0])
            roi_wo = random.randint(0, img.shape[1] - hair.shape[1])
            roi = img[roi_ho:roi_ho + h_height, roi_wo:roi_wo + h_width]

            img2gray = cv2.cvtColor(hair, cv2.COLOR_BGR2GRAY)
            ret, mask = cv2.threshold(img2gray, 10, 255, cv2.THRESH_BINARY)
            mask_inv = cv2.bitwise_not(mask)
            img_bg = cv2.bitwise_and(roi, roi, mask=mask_inv)
            hair_fg = cv2.bitwise_and(hair, hair, mask=mask)

            dst = cv2.add(img_bg, hair_fg, dtype=cv2.CV_64F)
            img[roi_ho:roi_ho + h_height, roi_wo:roi_wo + h_width] = dst

        return img
